# Generated by Django 2.2.3 on 2020-04-02 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0002_auto_20200402_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='timecreated',
        ),
        migrations.AddField(
            model_name='page',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reviews',
            name='datecreated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
