# Generated by Django 2.2.3 on 2020-04-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0004_auto_20200402_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
    ]
