# Generated by Django 2.2.3 on 2020-04-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0007_auto_20200402_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='madeby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_view.User'),
        ),
    ]
