# Generated by Django 2.2.3 on 2020-04-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0010_auto_20200402_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
