# Generated by Django 2.2.3 on 2020-04-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0012_auto_20200402_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
