# Generated by Django 2.2.3 on 2020-04-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0015_auto_20200404_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='madeby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='gamer_view.UserProfile'),
        ),
    ]
