# Generated by Django 2.2.3 on 2020-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0019_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
