# Generated by Django 2.2.3 on 2020-04-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_view', '0021_auto_20200405_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gamename',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_view.Page'),
        ),
    ]
